export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_STUDENT = 'GET_STUDENT';

export const DELETE_COURSE = 'DELETE_COURSE';
export const DELETE_COURSETYPE = 'DELETE_COURSETYPE'

export const GET_COURSES = 'GET_COURSES';
export const GET_COURSETYPE = 'GET_COURSETYPE';
export const FETCH_COURSETYPE = 'FETCH_COURSETYPE';

export const GET_ENROLLEDSTUDENTS = 'GET_ENROLLEDSTUDENTS';
